### ISSUE TITLE
Computer does not wake up

### ISSUE THREAD

**Issue by edtst** [DiedB/it.diederik.wol#1]
I put the Mac address in the test field in the form 00:00:00... but it won't wake up. The flow does run and I see a circle spinning in the WOL card.

I used a WOL utillity on my wifi laptop and this does wake up my computer.

**Comment by DiedB** [comment]
There is a bug in the Homey argument field (where you put in the MAC). When getting the field value, Homey sometimes returns the value with the div tags around it, and the module used for WOL obviously doesn't understand this and throws an error.

I will push an update in the next 10 minutes which will work around this (by removing the div tags). If it still doesn't work, try typing in the MAC address instead of pasting it. Probably some encoding issue.

Please let me know if the update fixes the problem.

**Comment by edtst** [comment]
I'll have to wait until it arrives in the app store. Meanwhile I tried typing the MAC address by hand in 1.0.0 but that doesn't work either.

**Comment by DiedB** [comment]
Update has been approved for the app store.

**Comment by DiedB** [comment]
I haven't been able to pinpoint the exact cause of the bug, since it only happens sometimes (when it works, it keeps working though). Can you try removing the app completely, removing the associated flows, and then set it up again, by typing in the MAC address in the given format (01:23:45:AB:CD:EF). According to the comments in the app store, it does work for me and others in 1.0.0.

**Comment by edtst** [comment]
OK, it still says 1.0.0 here. I’ll wait.

Update has been approved for the app store.

**Comment by edtst** [comment]
Version 1.0.1 still not in the app store. Any idea?

**Comment by DiedB** [comment]
It is still pending, takes a long time apparently :/

Op zo 21 feb. 2016 om 14:10 schreef edtst notifications@github.com:

**Comment by edtst** [comment]
I tried 1.0.1 and still no luck

**Comment by edtst** [comment]
any news?

**Comment by DiedB** [comment]
Not at all, it seems to be working for others. Could you run it in debug
mode? Download the code from GitHub and use athom-cli to upload the app. It
will show you errors on the command line.

**Comment by edtst** [comment]
No sorry I'll try some apps on an iPad to see where the problem is.

**Comment by DiedB** [comment]
I have pushed out an update which has some better error reporting. Can you try it and describe what happens? Do you get a green check when testing the flow or does the app give you an error?

First check if you are on 1.0.2, it should be updated today.

**Comment by DiedB** [comment]
I didn't receive a reply, I assume this issue can be closed.
