### ISSUE TITLE
Can't add device

### ISSUE THREAD

**Issue by ghost** [DiedB/it.diederik.wol#5]
Hello,
today i downloaded your app to homey but I cant add device. After I put MAC address and name to required fields and click Add the screen just goes back to Devices and my WOL device wasnt added. Can you help me please ?

**Comment by sHiKoRa** [comment]
Unfortunately I have exactly the same issue.

**Comment by DiedB** [comment]
What Homey firmware version are you both running?

**Comment by sHiKoRa** [comment]
Thanks for your response DiedB! I'm currently on the latest stable Homey version 4.2.0 and Homey-WakeOnLan version 2.0.0. If you want I can generate a diagnostics report. I have the app running probably since the beginning I would say end of 2018, devices added before are working fine. The only issue I have is not being able to add new devices somehow. It is really a great app and for me a must have on Homey! Thanks for developing and maintaining it!

**Comment by DiedB** [comment]
Could you try this version?

https://homey.app/nl-nl/app/it.diederik.wol/Wake-on-LAN/test/

**Comment by sHiKoRa** [comment]
Thanks for your feedback. The new WOL app requires Homey firmware 5. I'm a bit sceptic to install the Homey v5.0.0-rc.50 since it is not the stable version and have bad experience from the past with RC versions. If I just have to wait until I'm on the version 5.0 that is fine with me too.

**Comment by DiedB** [comment]
I understand, probably won't take too long for v5 to release. I'm pretty sure this should fix the problem, although I have no idea what causes you to not be able to add devices.

**Comment by sHiKoRa** [comment]
Thank you for the feedback! I will let you know if the problem is resolved once my Homey has been updated to version 5.

**Comment by DiedB** [comment]
The SDK v3 version of the app has been released, does it work now?

**Comment by sHiKoRa** [comment]
Yes indeed it has been resolved. I've just tested it and it works like a charm. Thx for your support, I really appreciate it!
